"""add_poc_invitations_table

Revision ID: 18d611cbe1a3
Revises: 7d69c593693f
Create Date: 2026-01-31 01:48:15.035866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18d611cbe1a3'
down_revision: Union[str, None] = '7d69c593693f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poc_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poc_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'FAILED', 'REVOKED', name='pocinvitationstatus'), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=True),
    sa.Column('personal_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('resend_count', sa.Integer(), nullable=True),
    sa.Column('last_resent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['poc_id'], ['pocs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poc_invitations_email'), 'poc_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_poc_invitations_id'), 'poc_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_poc_invitations_token'), 'poc_invitations', ['token'], unique=True)
    op.alter_column('poc_diagrams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_poc_diagrams_poc_id', table_name='poc_diagrams')
    op.drop_index('ix_task_group_tasks_task_group_id', table_name='task_group_tasks')
    op.drop_index('ix_task_group_tasks_task_id', table_name='task_group_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_group_tasks_task_id', 'task_group_tasks', ['task_id'], unique=False)
    op.create_index('ix_task_group_tasks_task_group_id', 'task_group_tasks', ['task_group_id'], unique=False)
    op.create_index('ix_poc_diagrams_poc_id', 'poc_diagrams', ['poc_id'], unique=False)
    op.alter_column('poc_diagrams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_poc_invitations_token'), table_name='poc_invitations')
    op.drop_index(op.f('ix_poc_invitations_id'), table_name='poc_invitations')
    op.drop_index(op.f('ix_poc_invitations_email'), table_name='poc_invitations')
    op.drop_table('poc_invitations')
    # ### end Alembic commands ###
